# Generated by Django 4.2 on 2025-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_points',
            field=models.PositiveIntegerField(default=10, help_text='Максимальное количество баллов за это задание.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_uploads',
            field=models.PositiveIntegerField(default=20, help_text='Максимальное количество загрузок для студента.'),
        ),
    ]
